algoritmo foo;
const 
	esx = 1;
	pi = 3.1415;
	msg = "H";
fconst
	ent x: entero;
{Prec: Ejemplo en donde se declaran símbolos de distinto tipo: ctes, variables y literales. Mirar la tabla de simbolos para ver los símbolos almacenados}
var 
	a,b : entero;
	c : real;
	letra : caracter;
	texto : cadena;
	e : booleano;
fvar
a := b + (c * 4) / pi;
e := falso o (verdadero y e)

{Post: ...  }
falgoritmo
