algoritmo foo;
	const 
		pi = 3.1415;
		msg = 'Hello World';
		msg = "H";
		esx = 1;
	fconst
	ent x: entero;
{Prec: Ejemplo en donde se declaran símbolos de distinto tipo: ctes, variables y literales. Mirar la tabla de simbolos para ver los símbolos almacenados}
var 
	a,b : entero;
	c : real;
	letra : caracter;
	texto : cadena;
	e : booleano;
fvar
a := b + (c * 4) / pi;
e := falso o (verdadero = e)

{Post: ...  }
falgoritmo
